### ISSUE TITLE
Clarification on a comment

### ISSUE THREAD

**Issue by simo955** [slinderman/pyhawkes#21]
Hi, first of all thank you for the great work. I was looking into your code and I need a clarification on a comment made at line 1425 in pyhawkes/models.py. Isn't that part referring to the initialisation of a Continuous Time Network Hawkes Model, instead of Discrete. Am I wrong?
Thank you for the clarification

![code](https://user-images.githubusercontent.com/26788103/73977555-96f5c580-48f8-11ea-9851-fbfc103d030f.png)

**Comment by slinderman** [comment]
Apologies for the confusion.  Fixed in https://github.com/slinderman/pyhawkes/commit/0df433a40c5e6d8c1dcdb98ffc88fe3a403ac223.
