### ISSUE TITLE
clang-omp no longer supported

### ISSUE THREAD

**Issue by ulfaslak** [slinderman/pyhawkes#5]
Not an expert on the matter, all I can say is that clang no longer supports openmp, so the MAC OSX instructions are no longer valid. Can't do 'brew install clang-omp' either.

**Comment by JeongMinCha** [comment]
The same issue on me.
The version of brew on my mac is like
```
$ brew -v
Homebrew 1.1.7
Homebrew/homebrew-core (git revision b79b3; last commit 2017-01-20)
```

**Comment by JeongMinCha** [comment]
I found something which may be our solution :)
I would try it and get back when I am done.
http://discourse.brew.sh/t/there-is-no-longer-a-clang-omp-formula-for-macos-sierra/47
This link says that we should install "llvm" instead of "clang-omp" because it is deprecated.

**Comment by JeongMinCha** [comment]
I tried but couldn't solve the problem. 
I think that the codes in this project should be improved to use llvm or something else instead of clang-omp because clang-omp is deprecated.

**Comment by JeongMinCha** [comment]
Okay, I found a solution.
```
brew tap homebrew/boneyard
brew install clang-omp
```
I think it's not a perfect solution but you can do that temporarily.
I also suggest that we improve codes in this repository to use another ways instead of "clang-omp" because the plugin is not to be used now.

**Comment by slinderman** [comment]
Thanks for the heads up.  I would like to make the dependency on OpenMP optional so that it "just works" for most users.  Honestly, I think the best way to compile is via gcc, but I realize that not everyone likes that option.

**Comment by jeongmincha** [comment]
@slinderman How about using llvm? I don't know how hard it would be, but using llvm over clang-omp seems the best option.

**Comment by slinderman** [comment]
Hi all, 
I've made some changes to the installation process to make GSL and OpenMP optional.  Please see issue https://github.com/slinderman/pyhawkes/issues/10.  The short story is that default installation via `pip install pyhawkes` or `python setup.py install` should work out of the box for most users, but the default version won't take advantage of multithreading.  For advanced users, I've updated the instructions on how to compile with GSL and OpenMP support using the GNU gcc and g++ compilers. 

If you have a second, please give the new installation procedure(s) a shot and see if they work for you.

Thanks,
Scott
